-- _D2DEMO Table
CREATE TABLE _D2DEMO (
    foldername VARCHAR(255) NOT NULL,
    ETHN_GRP_CAT_TXT ENUM('Unknown','Not Hispanic or Latino','Not Reported','Hispanic or Latino'),
    PERSON_GENDER ENUM('Female','Male'),
    COUNTRY_CD VARCHAR(15),
    ZIPCODE NUMERIC(20),
    PAYMENT_METHOD VARCHAR(50),
    RACE_CAT_TXT ENUM('White', 'Black', 'Asian', 'Hispanic', 'Other'),
    newID INT NOT NULL,
    PRIMARY KEY (newID)
) ENGINE=InnoDB; 

CREATE TABLE MED_COND_TYPE (
  MED_COND_TYPEID INT NOT NULL AUTO_INCREMENT,
  `Condition` VARCHAR(255) NOT NULL,
  PRIMARY KEY (MED_COND_TYPEID)
);




-- DROP TABLE IF EXISTS _D2MEDHXLG;
CREATE TABLE _D2MEDHXLG (
  D2MEDHXLGID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  OTH_AERO_DIG_DX VARCHAR(255),
  MED_COND_TYPE INT,
  MED_COND_YNUNK VARCHAR(255),
  MED_COND_DX_DAYS VARCHAR(255),
  MED_COND_DESC VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2MEDHXLGID),
  FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID),
  FOREIGN KEY (MED_COND_TYPE)
    REFERENCES MED_COND_TYPE (MED_COND_TYPEID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;





-- Patient table and Initial eligibility check relationship
CREATE TABLE _D2ELIGCHECK (
    D2ELIGCHECKID INT NOT NULL AUTO_INCREMENT,
    foldername VARCHAR(255) NOT NULL,
    AGE  VARCHAR(255),
    PT_SIGN_CNSNT VARCHAR(255) NOT NULL,
    CNSNT_DAYS VARCHAR(255) NOT NULL,
    PT_AGE_5079_YN VARCHAR(255) NOT NULL,
    LUNG_HX_QUES_YN VARCHAR(255) NOT NULL,
    BIO_SPEC_TOL_YN VARCHAR(255) NOT NULL,
    PT_HX_COPD_EMP_YN VARCHAR(255) NOT NULL,
    REL_LG_CX_YN VARCHAR(255) NOT NULL,
    GRPB_SMK_STS VARCHAR(255) NOT NULL,
    PT_SMK_10_25_YRS VARCHAR(255) NOT NULL,
    PT_SMK_CIG_DAY VARCHAR(255) NOT NULL,
    PT_20_PK_YRS VARCHAR(255) NOT NULL,
    GRP_B_PK_YRS VARCHAR(255) NOT NULL,
    FIBOPT_BRONCH_YN VARCHAR(255) NOT NULL,
    SOC_COMPL_YN VARCHAR(255) NOT NULL,
    DX_LNG_CX VARCHAR(255) NOT NULL,
    CON_IND_NBRSH_FIBBRN_YN VARCHAR(255) NOT NULL,
    ALLG_ANT_YN VARCHAR(255) NOT NULL,
    PT_WT_GRT_CT VARCHAR(255) NOT NULL,
    newID INT NOT NULL,
    PRIMARY KEY (D2ELIGCHECKID),
    
        FOREIGN KEY (newID)
        REFERENCES _D2DEMO (newID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB;





-- Previous surgical history and Patient table relationship

CREATE TABLE _D2SURGHX (
    D2SURGHXID INT NOT NULL AUTO_INCREMENT,
    foldername VARCHAR(255),
    THRC_SURG_HX_YN VARCHAR(25),
    SURG_PROC_TYPE VARCHAR(255),
    SURG_PROC_DESC VARCHAR(255),
    SURG_PROC_DAYS VARCHAR(255),
    newID INT NOT NULL,
    PRIMARY KEY (D2SURGHXID),
    
        FOREIGN KEY (newID)
        REFERENCES _D2DEMO (newID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE `_EXPOSURE_TYPE` (
  `exposureID` INT NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`exposureID`)
);



CREATE TABLE _D2PCOCCEXPHX (
    D2PCOCCEXPHXID INT NOT NULL AUTO_INCREMENT,
    foldername VARCHAR(255) ,
    PT_COMPL_OCCE_PTBLANK VARCHAR(255) NOT NULL,
    PT_COMPL_WRK_GRTR_1YR VARCHAR(255) NOT NULL,
    PT_COMPL_OCC_EXP INT,
    OCC_EXP_OTH_SPEC VARCHAR(255),
    PT_COMPL_NUM_MOS_EXP VARCHAR(255),
    PT_COMPL_NUM_YRS_EXP VARCHAR(255),
    PT_COMPL_EXP_TM_BLNK VARCHAR(255),
    PT_COMPL_LGTH_EXP VARCHAR(255),
    PT_COMPL_EXP_EFF VARCHAR(255),
    newID INT NOT NULL,
    PRIMARY KEY (D2PCOCCEXPHXID),
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID),
    FOREIGN KEY (PT_COMPL_OCC_EXP)
    REFERENCES _EXPOSURE_TYPE (exposureID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;





CREATE TABLE _D2PCMEDHXCOND (
    D2PCMEDHXCONDID INT NOT NULL AUTO_INCREMENT,
    foldername VARCHAR(255) ,
    PT_COMPL_WT VARCHAR(255),
    PT_COMPL_WT_PTBLANK VARCHAR(255),
    PT_COMPL_HT_FEET VARCHAR(255),
    PT_COMPL_HT_INCH VARCHAR(255),
    PT_COMPL_HT_PTBLANK VARCHAR(255),
    PT_COMPL_DX_PTBLK VARCHAR(255),
    PT_COMPL_DX VARCHAR(255),
    PT_REP_COND_ILL INT,
    PT_REP_AGE_FST_DX VARCHAR(255),
    PT_COMPL_AGE_BLNK VARCHAR(255),
    newID INT NOT NULL,
    PRIMARY KEY (D2PCMEDHXCONDID),
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID),
    FOREIGN KEY (PT_REP_COND_ILL)
    REFERENCES MED_COND_TYPE (MED_COND_TYPEID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;





CREATE TABLE CANCER_TYPE (
    cancerID INT NOT NULL AUTO_INCREMENT,
    cancer_condition VARCHAR(255) NOT NULL,
    PRIMARY KEY (cancerID)
) ENGINE=InnoDB;




CREATE TABLE _D2PCMEDHXCAN (
  D2PCMEDHXCANID INT NOT NULL auto_increment,
  foldername VARCHAR(255) NOT NULL,
  PT_REP_FAM_CX_FAT VARCHAR(255),
  PT_REP_FAM_CX_MOT VARCHAR(255),
  PT_REP_FAM_CX_BRO VARCHAR(255),
  PT_REP_FAM_CX_SIS VARCHAR(255),
  PT_REP_FAM_CX_CHILD VARCHAR(255),
  PT_COMPL_CX_PTBLK VARCHAR(255),
  PT_COMPL_DX VARCHAR(255),
  PT_REP_CX INT,
  CX_OTH_SPEC VARCHAR(255),
  PT_REP_AGE_FST_DX VARCHAR(255),
  PT_CX_AGE_BLNK VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PCMEDHXCANID),
  FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID),
    FOREIGN KEY (PT_REP_CX)
    REFERENCES CANCER_TYPE (cancerID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);


-- 
CREATE TABLE _D2DEMO_D2PCMEDHXCAN_CANCER_TYPE (
    D2PCMEDHXCANID INT NOT NULL,
    cancerID INT NOT NULL,
    newID INT NOT NULL,
    PRIMARY KEY (D2PCMEDHXCANID, cancerID),
    CONSTRAINT fk__D2DEMO_D2PCMEDHXCAN_CANCER_TYPE_D2DEMO
        FOREIGN KEY (newID)
        REFERENCES _D2DEMO (newID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk__D2DEMO_D2PCMEDHXCAN_CANCER_TYPE_D2PCMEDHXCAN
        FOREIGN KEY (D2PCMEDHXCANID)
        REFERENCES _D2PCMEDHXCAN (D2PCMEDHXCANID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk__D2DEMO_D2PCMEDHXCAN_CANCER_TYPE_CANCER_TYPE
        FOREIGN KEY (cancerID)
        REFERENCES CANCER_TYPE (cancerID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB;



-- Patient pulmonary symptoms and patient table
CREATE TABLE _D2PCSYMPCBE (
  D2PCSYMPCBEID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  PT_COMPL_CGH VARCHAR(255),
  PT_COMPL_CGH_4_6_YNU VARCHAR(255),
  PT_COMPL_CGH_MORN_YN VARCHAR(255),
  PT_COMPL_CGH_DY_NT_YN VARCHAR(255),
  PT_COMPL_CGH_3MOS_YN VARCHAR(255),
  PT_COMPL_CGH_YRS VARCHAR(255),
  CGH_YRS_PTBLANK VARCHAR(255),
  PT_COMPL_SBRTH_YN VARCHAR(255),
  PT_COMPL_SBRHT_WSLW_YN VARCHAR(255),
  PT_COMPL_SBRTH_100YDS_YN VARCHAR(255),
  PT_COMPL_SBRTH_HS_YN VARCHAR(255),
  PT_COMPL_SBRTH_YRS VARCHAR(255),
  SBRTH_YRS_PTBLNK VARCHAR(255),
  PT_COMPL_COPD_EX VARCHAR(255),
  COPD_EX_PTBLNK VARCHAR(255),
  PT_COMPL_COPD_EX_HOS VARCHAR(255),
  COPD_EX_HOS VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PCSYMPCBEID),
  
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;


-- Patient phlegm symptoms and alcohol history and patient table relationship
CREATE TABLE _D2PCSYMPPHL (
  D2PCSYMPPHLID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  PT_COMPL_PHL_CH_YN VARCHAR(255),
  PT_COMPL_PHL_OCC VARCHAR(255),
  PT_COMPL_PHL_MORN VARCHAR(255),
  PT_COMPL_PHL_NGT VARCHAR(255),
  PT_COMPL_PHL_MOS VARCHAR(255),
  PT_COMPL_PHL_YRS VARCHAR(255),
  PHL_YRS_PTBLNK VARCHAR(255),
  PT_COMPL_ALC_HX_YN VARCHAR(255),
  PT_COMPL_ALC_CUR_YN VARCHAR(255),
  PT_COMPL_ALC_HX_FRMR VARCHAR(255),
  PT_COMPL_ALC_YRS VARCHAR(255),
  ALC_YRS_PTBLNK VARCHAR(255),
  PT_COMPL_DRNK_WK VARCHAR(255),
  DRNK_WK_PTBNLK VARCHAR(255),
  PT_COMPL_24HR_ALC_NUM VARCHAR(255),
  H24R_ALC_NUM_PTBLNK VARCHAR(255),
  ALC_WK_YR_PTBNLK VARCHAR(255),
  PT_COMPL_ALC_WK VARCHAR(255),
  PT_COMPL_ALC_LST_YR VARCHAR(255),
  PT_COMPL_ALC_3YRS VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PCSYMPPHLID),
  
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;


-- Patient smoking status and patient table relationship
CREATE TABLE _D2PCSMKHX (
  D2PCSMKHXID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  PT_COMPL_SMOK_STAT VARCHAR(255),
  PT_COMPL_SMOK_HAB VARCHAR(255),
  PT_COMPL_CIG_DAY VARCHAR(255),
  CIG_DAY_PTBLNK VARCHAR(255),
  PT_COMPL_YRS_SMOKE VARCHAR(255),
  YRS_SMOKE_PTBLNK VARCHAR(255),
  PT_COMPL_1ST_SMK VARCHAR(255),
  ST1_SMOKE_PTBLNK VARCHAR(255),
  PT_COMPL_1ST_SMK_DIZ VARCHAR(255),
  PT_COMPL_1ST_SMK_RUSH VARCHAR(255),
  PT_COMPL_DAILY_SMK VARCHAR(255),
  DAILY_SMK_PTBLNK VARCHAR(255),
  PT_COMPL_SMK_MOST_DAY VARCHAR(255),
  SMK_MOST_DAY_PTBLNK VARCHAR(255),
  PT_COMPL_NSMK_3MOS VARCHAR(255),
  NSML_3MOS_PTBLNK VARCHAR(255),
  PT_COMPL_NSMK_LOC VARCHAR(255),
  PT_COMPL_SMK_MORE VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PCSMKHXID),
  
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- Patient secondhand smoking exposure and Patient table relationship
CREATE TABLE _D2PC2NDSMK (
  D2PC2NDSMKID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  PT_COMPL_LIV_SMKR VARCHAR(255),
  PT_COMPL_CUR_LIV_SMRK VARCHAR(255),
  PT_COMPL_NUM_SMKR VARCHAR(255),
  NUM_SMKR_PTBLNK VARCHAR(255),
  PT_COMPL_WRK_SMKR VARCHAR(255),
  PT_COMPL_CUR_WRK_SMKR VARCHAR(255),
  PT_COMPL_NUM_WRK VARCHAR(255),
  NUM_WRK_PTBLNK VARCHAR(255),
  PT_COMPL_WRK_YRS VARCHAR(255),
  WRK_YRS_PTBLNK VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PC2NDSMKID),
  
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;


-- Patient highest education, marriage status, income and family members and Patient Table relationship
CREATE TABLE _D2PCDEMO (
  D2PCDEMOID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  PT_COMPL_SCHOOL VARCHAR(255),
  PT_COMPL_MRTL_STS VARCHAR(255),
  PT_COMPL_HSHLD_INC VARCHAR(255), 
  PT_COMPL_NM_SP_INC VARCHAR(255),
  NM_SP_INC_PTBLNK VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PCDEMOID),
  
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;


-- Patient vitals from physical exam and Patient table relationship

CREATE TABLE _D2PHYEXAM (
  D2PHYEXAMID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255) NOT NULL,
  PHY_EXAM_DAYS VARCHAR(255),
  PT_WT VARCHAR(255),
  PT_HT VARCHAR(255),
  PULSE_RATE_MSRMT_VAL VARCHAR(255),
  BLD_PRESS_SYSTOLIC VARCHAR(255),
  BLD_PRESS_DIASTOLIC VARCHAR(255),
  PT_TEMP VARCHAR(255),
  P_VS_RR_PHYSEXM_VAL VARCHAR(255),
  BDY_SYS_SITE_NM VARCHAR(255),
  BDY_SITE_OTH_SPC VARCHAR(255),
  BDY_SYS_IND VARCHAR(255),
  BDY_SYS_IND_ABN_DSC VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PHYEXAMID),
 
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;



--     OJ Tables begin here --
DROP TABLE _D2PFT;
CREATE TABLE _D2PFT (
  D2PFTID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255),
  RVW_QUALITY VARCHAR(255),
  RVW_AGREE_DATA VARCHAR(255),
  RVW_COMM VARCHAR(255),
  PULM_FCT_TST_YN VARCHAR(255),
  PULM_FCT_TST_ND VARCHAR(255),
  PFT_PREPOST VARCHAR(255),
  PFT_DAYS VARCHAR(255),
  FVC_RS VARCHAR(255),
  FVC_RS_PER VARCHAR(255),
  FEV_RS VARCHAR(255),
  FEV_RS_PER VARCHAR(255),
  FEV_FVC VARCHAR(255),
  FEF_2575_VAL VARCHAR(255),
  FEF_2575_VAL_PER VARCHAR(255),
  FULL_PULM_TST_PRF_YN VARCHAR(255),
  FULL_PULM_TST_DAYS VARCHAR(255),
  TOT_LUNG_CAP VARCHAR(255),
  TOT_LUNG_CAP_PR VARCHAR(255),
  RESLUNG_VOL_PER VARCHAR(255),
  RESLUNG_VOL VARCHAR(255),
  DLCO_ACT VARCHAR(255),
  DLCO_RS VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2PFTID),
  CONSTRAINT fk_newID
    FOREIGN KEY (newID)
    REFERENCES _D2DEMO (newID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

--      --
DROP TABLE IF EXISTS _D2BSBRONCH;

CREATE TABLE _D2BSBRONCH (
  D2BSBRONCHID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255),
  BRNCHSPY_BX_COLL_YN VARCHAR(255),
  BRNCHSPY_BX_COLL_ND VARCHAR(255),
  BRNCHSPY_BX_COLL_DAYS VARCHAR(255),
  SED_GVN_YN VARCHAR(255),
  RT_SED_ADMIN VARCHAR(255),
  SED_TYPE VARCHAR(255),
  LOC_ANEST_USED_YN VARCHAR(255),
  LOC_ANEST_USED_TYPE VARCHAR(255),
  BRNCHSPY_TIS_OBT_YN VARCHAR(255),
  NRMCHSPY_TIS_OBT_ND VARCHAR(255),
  AE_YN VARCHAR(255),
  BRNCH_SITE_BP VARCHAR(255),
  BP_SAM_TYP VARCHAR(255),
  BRNCHSPY_BP_SLD VARCHAR(255),
  BRNCHSPY_FLR_RT VARCHAR(255),
  BRNCHSPY_FLR_RT_ND VARCHAR(255),
  DT_TM_80_IN_DAYS VARCHAR(255),
  FRZ_TEMP VARCHAR(255),
  SAMP_FRZ_THW VARCHAR(255),
  SAMP_FRZ_THW_COMM VARCHAR(255),
  ALQ_COMM VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2BSBRONCHID),
  
  FOREIGN KEY (newID)
  REFERENCES _D2DEMO (newID)
  ON UPDATE CASCADE
  ON DELETE CASCADE
) ENGINE=InnoDB;

--               --
CREATE TABLE _D2BSBLOOD (
  D2BSBLOODID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255),
  BLD_COLL_YN VARCHAR(255),
  BLD_COLL_ND_RSN VARCHAR(255),
  BLD_COLL_DAYS VARCHAR(255),
  BLD_COLL_TB_TYPE VARCHAR(255),
  BL_COLL_TB_COLL VARCHAR(255),
  BL_COLL_TB_NCLL_RSN VARCHAR(255),
  AE_YN VARCHAR(255),
  BLD_COLL_PLSM_YN VARCHAR(255),
  PLSM_PROC_2HRS_YN VARCHAR(255),
  PLSM_CENT_IMM_YN VARCHAR(255),
  PLSM_NT_PRF_REAS TEXT,
  PLSM_PF_PROT_YN VARCHAR(255),
  PLSM_PF_PROT_REAS TEXT,
  BLD_COLL_BUFFY_YN VARCHAR(255),
  BUFFY_NT_PRF_REAS TEXT,
  BUFFY_PF_PROT_YN VARCHAR(255),
  BUFFY_PF_PROT_REAS TEXT,
  BLD_COLL_SERUM_YN VARCHAR(255),
  SERUM_NT_PRF_REAS TEXT,
  SERUM_PF_PROT_YN VARCHAR(255),
  SERUM_PF_PROT_REAS TEXT,
  BLD_COLL_PAX_YN VARCHAR(255),
  PAX_NT_PRF_REAS TEXT,
  PAX_PF_PROT_YN VARCHAR(255),
  PAX_PF_PROT_REAS TEXT,
  BLD_COLL_STRECK_YN VARCHAR(255),
  STRECK_NT_PRF_REAS TEXT,
  STRECK_PF_PROT_YN VARCHAR(255),
  STRECK_PROT_REAS TEXT,
  BLD_COLL_PBMC_YN VARCHAR(255),
  PBMC_PF_PROT_REAS TEXT,
  PBMC_PF_PROT_YN VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2BSBLOODID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO(newID)
) ENGINE=InnoDB;

-- --
CREATE TABLE _D2BSBRONCHBRUSH (
  D2BSBRONCHBRUSHID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255),
  ENDOBRON_BRSH_COLL_YN VARCHAR(255),
  ENDOBRON_BRSH_ND VARCHAR(255),
  ENDOBRON_TMPT VARCHAR(255),
  ENDOBRON_BRSH_PR_YN VARCHAR(255),
  ENDOBRON_BRSH_PR VARCHAR(255),
  ENDOBRON_BRSH_COLL_DAYS VARCHAR(255),
  AE_YN VARCHAR(255),
  ENDOBRON_TYPE VARCHAR(255),
  EPPEN_TUBE_CONT VARCHAR(255),
  ENDOBRON_COLL VARCHAR(255),
  DT_TM_80_IN_DAYS VARCHAR(255),
  FRZ_TEMP VARCHAR(255),
  SAMP_FRZ_THW VARCHAR(255),
  SAMP_FRZ_THW_COMM VARCHAR(255),
  ALQ_COMM VARCHAR(255),
  newID INT,
  PRIMARY KEY (D2BSBRONCHBRUSHID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO(newID)
) ENGINE=InnoDB;



-- -- 
CREATE TABLE _D2BSURINE (
  D2BSURINEID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255),
  URN_SAMP_YN ENUM('Yes', 'No'),
  URN_SAMP_NCOLL_REAS VARCHAR(255),
  URN_SAMP_DAYS INT,
  URN_SAMP_COLL_PR VARCHAR(255),
  URN_NOT_PR_REAS VARCHAR(255),
  AE_YN ENUM('Yes', 'No'),
  URN_COLL_TYP VARCHAR(255),
  URN_COLL VARCHAR(255),
  DT_TM_80_IN_DAYS INT,
  FRZ_TEMP VARCHAR(255),
  SAMP_FRZ_THW VARCHAR(255),
  SAMP_FRZ_THW_COMM VARCHAR(255),
  ALQ_COMM VARCHAR(255),
  newID INT,
  PRIMARY KEY (D2BSURINEID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO(newID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;




-- --
CREATE TABLE _D2BSBUCCAL (
  D2BSBUCCALID INT NOT NULL AUTO_INCREMENT,
  foldername VARCHAR(255),
  BUCCAL_SAMP_YN ENUM('Yes', 'No'),
  BUCCAL_SAMP_ND_REAS VARCHAR(255),
  BUCCAL_ND_PR ENUM('Yes', 'No'),
  BCCL_ND_PR_REAS VARCHAR(255),
  BUCCAL_SAMP_DAYS INT,
  AE_YN ENUM('Yes', 'No'),
  BCCL_TYPE VARCHAR(255),
  BCCL_COLL VARCHAR(255),
  DT_TM_80_IN_DAYS INT,
  FRZ_TEMP VARCHAR(255),
  SAMP_FRZ_THW VARCHAR(255),
  SAMP_FRZ_THW_COMM VARCHAR(255),
  ALQ_COMM VARCHAR(255),
  newID INT NOT NULL,
  PRIMARY KEY (D2BSBUCCALID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO (newID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE TABLE _D2BSSPUTUM(
   
   D2BSSPUTUMID INT NOT NULL AUTO_INCREMENT,
   foldername       VARCHAR(40) 
  ,SPUTUM_SAMP_YN   VARCHAR(40) 
  ,SPUTUM_SAMP_ND   VARCHAR(192) 
  ,SPUTUM_SAMP_DAYS VARCHAR(40) 
  ,AE_YN            VARCHAR(40) 
  ,newID            INTEGER  NOT NULL,
  PRIMARY KEY (D2BSSPUTUMID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO (newID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE _D2FU(
   D2FUID INT NOT NULL AUTO_INCREMENT,
   foldername       VARCHAR(20) 
  ,FU_YN            VARCHAR(20) 
  ,FU_ND_REAS       VARCHAR(128) 
  ,FU_DAYS          VARCHAR(20) 
  ,AE_FU_YN         VARCHAR(20) 
  ,PULM_FCT_TST_YN  VARCHAR(20) 
  ,PHY_EXAM_YN      VARCHAR(70) 
  ,PHY_EXAM_ND      VARCHAR(120) 
  ,IMAG_YN          VARCHAR(70) 
  ,IMAG_TYPE        VARCHAR(28) 
  ,IMAG_DAYS        VARCHAR(40) 
  ,SURG_YN          VARCHAR(70) 
  ,SURG_DAYS        VARCHAR(40) 
  ,SURG_SAMP_YN     VARCHAR(30) 
  ,SURG_SAMP_ND_RSN VARCHAR(82) 
  ,newID            INTEGER  NOT NULL,
PRIMARY KEY (D2FUID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO (newID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;



CREATE TABLE _D2FUVITALSTATUS(
   D2FUVITALSTATUSID INT NOT NULL AUTO_INCREMENT,
   foldername         VARCHAR(16) 
  ,VS_TX_COMP_YN      VARCHAR(30) 
  ,VS_TX_ND_REAS      VARCHAR(123) 
  ,VS_TX_DAYS         VARCHAR(40) 
  ,PT_VS              VARCHAR(70) 
  ,DT_DEATH_DAYS      VARCHAR(4) 
  ,DEATH_REAS         VARCHAR(43) 
  ,MLGY_LUNG_YN       VARCHAR(3) 
  ,MLGY_LUNG_ORG      VARCHAR(12) 
  ,CN_SITE_ORG        VARCHAR(2) 
  ,LG_MLG_PRE_RPT_YN  VARCHAR(3) 
  ,DT_FRST_DX_DAYS    VARCHAR(4) 
  ,LG_CX_TYPE         VARCHAR(26) 
  ,LG_CX_HIST_CLS     VARCHAR(23) 
  ,LG_CX_HIST_SBTYP   VARCHAR(7) 
  ,NSM_CELL_LG_CS_STG VARCHAR(4) 
  ,LUNG_CS_PRV_REP_YN VARCHAR(7) 
  ,LG_MLG_PRG_DAYS    VARCHAR(4) 
  ,LUNG_CS_PROG_SITE  VARCHAR(18) 
  ,RSP_ST             VARCHAR(19) 
  ,RSP_ST_DAYS        VARCHAR(4) 
  ,TX_LG_CX_YN        VARCHAR(7) 
  ,newID              INTEGER  NOT NULL,
  PRIMARY KEY (D2FUVITALSTATUSID),
  FOREIGN KEY (newID) REFERENCES _D2DEMO (newID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;








CREATE TABLE __D2FUSTDYEVALDX(
   D2FUSTDYEVALDXID INT NOT NULL AUTO_INCREMENT,
   foldername         VARCHAR(20) 
  ,ST_EV_DX_COM_YN    VARCHAR(7) 
  ,ST_EV_DX_ND_RS     VARCHAR(106) 
  ,ST_EV_DAYS         VARCHAR(40) 
  ,MLGY_LUNG_YN       VARCHAR(90) 
  ,MLGY_LUNG_ORG      VARCHAR(22) 
  ,METS_SITE          VARCHAR(20) 
  ,DT_FRST_DAYS       VARCHAR(40) 
  ,LUNG_CS_PRV_REP_YN VARCHAR(30) 
  ,LG_MLG_PRG_DX      VARCHAR(30) 
  ,LG_MLG_PRG_DAYS    VARCHAR(40) 
  ,LUNG_CS_PROG_SITE  VARCHAR(18) 
  ,LG_CX_TYPE         VARCHAR(26) 
  ,LG_CX_HIST_CLS     VARCHAR(23) 
  ,LG_CX_HIST_SBTYP   VARCHAR(25) 
  ,LG_CX_STG          VARCHAR(40) 
  ,newID              INTEGER  NOT NULL,
PRIMARY KEY (D2FUSTDYEVALDXID),
FOREIGN KEY (newID) REFERENCES _D2DEMO (newID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;
